CONSTRUCTION_BILLING_PRJ/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include("accounts.urls")),
    path('companies/',include("company.urls")),
    path('projects/',include("project.urls")),
    path('consultants/',include("consultant.urls")),
    path('clients/',include("owner.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path,include,reverse_lazy
from . views import *
from django.contrib.auth import views as auth_views
app_name='accounts'
urlpatterns = [
    path('',LoginView,name='UserLogin'),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',success_url=reverse_lazy('accounts:PasswordResetDone'),
            email_template_name='accounts/password_reset_email.html',),name='PasswordReset'),
    path('password_reset_done/',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),name='PasswordResetDone'),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',success_url=reverse_lazy('accounts:PasswordResetComplete')),name='PasswordResetConfirm'),
    path('password_reset_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='PasswordResetComplete'),
    path('email_exists',ajax_email_exists,name='EmailExists'),
    path('email_exists_edit',ajax_email_exists_edit,name='EmailExistsEdit'),
    path('accounts/logout/', userlogout),
    path('accounts/login/', LoginView),
]

project/urls.py
from django.urls import path,include
from . views import *
app_name='project'
urlpatterns = [
    path('',dashboard,name='Dashboard'),
    path('manage',manage_project,name='ManageProject'),    
    path('edit',edit_project,name='EditProject'),   
    path('change_password',change_password,name='ChangePassword'),
    path('ajax_get_headings',ajax_get_headings,name='AjaxGetHeadings'),
    path('upload-status',get_upload_status, name='GetUploadStatus'),
    path('get_billupload_status',get_billupload_status, name='GetBillUploadStatus'),

    path('search_BoQ/<int:page>',search_boq_item,name='SearchItem'), 
    path('bill_of_quantities/<int:page>',manage_bill_of_quantities,name='ManageBOQ'),
    path('confirm_delete/<int:id>',confirm_delete_boq,name='ConfirmRemoveBOQ'),
    path('bill_of_quantities/delete',delete_bill_of_quantities,name='RemoveBOQ'),
    path('manage_item/<int:itemid>',manage_boq_item,name='ManageItem'), 
    path('remove_item/<int:itemid>',remove_boq_item,name='DeleteItem'), 

    path('boq_approvals',view_boq_approvals,name='ViewBoqApprovals'),
    path('remove_boq_update/<int:id>',remove_boq_update,name='RemoveBoqItemUpdate'),

    path('get_owners',ajax_get_owners,name='AjaxGetOwners'),
    path('get_companies',ajax_get_companies,name='AjaxGetCompanies'),
    path('get_consultants',ajax_get_consultants,name='AjaxGetConsultants'),

    path('add_consultant',add_consultant,name='AddConsultant'), 
    path('add_company',add_company,name='AddCompany'), 
    path('add_owner',add_owner,name='AddOwner'), 
    
    path('owner_comments/<int:measureid>',view_owner_comments,name='ViewOwnerComments'), 
    path('measurements/<int:itemid>/<int:page>',manage_measurements,name='Measurements'),
    path('edit_measurement/<int:measurementid>',edit_measurement,name='EditMeasurement'),
    path('remove_measurement/<int:measurementid>',remove_measurement,name='DeleteMeasurement'),
    path('workorder_boq/',upload_workorder_boq,name='UpLoadWOBOQ'),     
    path('bills/',create_bill,name='CreateBill'),
    path('create_new_bill/',create_new_bill,name='CreateNewBill'), 
    path('current_bill/<int:page>',current_bill,name='CurrentBill'), 
    path('save_current_bill',save_current_bill,name='SaveCurrentBill'),

    path('previous_bills',previous_bills,name='PreviousBills'), 
    path('previous_bills/<int:billid>/<int:page>',previous_bill,name='PreviousBill'), 
    path('previous_bills/measurements/<int:billid>/<int:itemid>/<int:page>',previous_bill_measurements,name='PreviousMeasurements'),
    path('edit_measurement/<int:measurementid>',edit_measurement,name='EditMeasurement'),
    path('remove_previous_measurement/<int:billid>/<int:measurementid>',remove_prev_measurement,name='DeletePreviousMeasurement'),
    path('search_item/<int:billid>/<int:page>',search_bill_item,name='SearchBillItem'), 
    path('share_to_consultant/<int:billid>',share_to_consultant,name='ShareToConsultant'),

    

    path('view_abstract/<int:billid>/<int:page>',viewAbstract,name='ViewAbstract'),
    path('generate_documents',generate_documents,name='Documents'),
    path('measurement_book/<int:billid>',downloadMBook,name='DownloadMBook'),
    
    path('logout_project/',userlogout,name='LogOutUser'),  
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.utils.timezone import now
'''
super admin ->add and manage company
admin -> create login for projects of companies
company -> has many projects and can view staus of each project
project-> project owned by a comapny and does all project related actions such as billing
'''
class User(AbstractUser):
    
    user_types = [
        ('super_admin', 'super_admin'),
        ('admin', 'admin'),
        ('project'  , 'project'),
        ('company', 'company'),
        ('consultant', 'consultant'),
        ('owner', 'owner'),
    ]
    
    user_type = models.CharField(max_length=30,choices=user_types)    
    added_by = models.CharField(max_length=30,default='super_admin')
    # def __str__(self):
    #     return "username = {}, user_type ={}".format(self.username, self.user_type)

    class Meta:
        db_table = 'User'


class Company(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    company_name=models.CharField(max_length=200,null=True)
    company_address=models.CharField(max_length=500,null=True)
    company_email=models.EmailField(null=True)
    country_code=models.CharField(max_length=4,default='+91')
    company_phone=models.CharField(max_length=10, validators=[RegexValidator(r'^\d{1,10}$')], help_text="Phone number without Country Code",null=True)
    # company_logo=models.CharField(max_length=500,null=True,blank=True)
    other_details=models.CharField(max_length=500,null=True,blank=True)
    def __str__(self):
        return "company_name = {}, companyuser ={}".format(self.company_name, self.user.username)

    class Meta:
        db_table = 'Company'


class Owner(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    owner_name=models.CharField(max_length=200,null=True,blank=True)
    owner_address=models.CharField(max_length=500,null=True,blank=True)
    owner_email=models.EmailField(null=True,blank=True)
    country_code=models.CharField(max_length=4,default='+91')
    owner_phone=models.CharField(max_length=10, validators=[RegexValidator(r'^\d{1,10}$')], help_text="Phone number without Country Code",null=True,blank=True)
    # consultant_logo=models.CharField(max_length=500,null=True,blank=True)
    other_details=models.CharField(max_length=500,null=True,blank=True)
    def __str__(self):
        return "owner = {}, owneruser ={}".format(self.owner_name, self.user.username)

    class Meta:
        db_table = 'Owner'

class Consultant(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    owner=models.ForeignKey(Owner,on_delete=models.CASCADE,null=True,blank=True)
    consultant_name=models.CharField(max_length=200,null=True,blank=True)
    consultant_address=models.CharField(max_length=500,null=True,blank=True)
    consultant_email=models.EmailField(null=True,blank=True) 
    country_code=models.CharField(max_length=4,default='+91')
    consultant_phone=models.CharField(max_length=10, validators=[RegexValidator(r'^\d{1,10}$')], help_text="Phone number without Country Code",null=True,blank=True)
    # consultant_logo=models.CharField(max_length=500,null=True,blank=True)
    other_details=models.CharField(max_length=500,null=True,blank=True)
    def __str__(self):
        return "Consultant = {}, consultantuser ={}".format(self.consultant_name, self.user.username)

    class Meta:
        db_table = 'Consultant'  




class Project(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    company=models.ForeignKey(Company,on_delete=models.CASCADE)
    project_name=models.CharField(max_length=500,null=True,blank=True)    
    owner=models.ForeignKey(Owner,on_delete=models.CASCADE,null=True)
    consultant=models.ForeignKey(Consultant,on_delete=models.CASCADE,null=True)
    contractor=models.CharField(max_length=500,default='self',null=True,blank=True)
    location=models.CharField(max_length=500,null=True,blank=True)
    work_order_no=models.CharField(max_length=150,null=True,blank=True)
    other_details=models.CharField(max_length=500,null=True,blank=True)
    def __str__(self):
        return "project = {}, projectuser= {}, company ={}".format(self.project_name,self.user.username, self.company.company_name)

    class Meta:
        db_table = 'Project'


class Bill(models.Model):
    bill_name=models.CharField(max_length=100,default='1')
    bill_number=models.IntegerField(default=1)
    project=models.ForeignKey(Project, on_delete= models.CASCADE)
    submitted=models.BooleanField(default=False)
    bill_date=models.DateField()
    shared_to_consultant=models.DateTimeField(null=True,blank=True,default=None)
    shared_to_owner=models.DateTimeField(null=True,blank=True,default=None)
    consultant_approved=models.DateTimeField(null=True,blank=True,default=None)
    owner_approved=models.DateTimeField(null=True,blank=True,default=None)
    
    other_details=models.CharField(max_length=500,null=True,blank=True)
    def __str__(self):
        return "{}th bill of {} project Bill Name : {}".format(self.bill_number,self.project.project_name,self.bill_name)

    def clean(self):        
        existing_bills = Bill.objects.filter(project=self.project, bill_name=self.bill_name)
        if self.pk:
            existing_bills = existing_bills.exclude(pk=self.pk)
        if existing_bills.exists():
            raise ValidationError('A bill with this name already exists for the project.')

    class Meta:
        db_table = 'Bill'
        constraints = [
            models.UniqueConstraint(fields=['project', 'bill_name'], name='unique_project_bill')
        ]



class WOBOQItem(models.Model):
    project=models.ForeignKey(Project, on_delete= models.CASCADE)
    serial_no=models.CharField(max_length=100,null=True,default=None)# enters '##' when no serialno for row
    description=models.CharField(max_length=100000,null=True,blank=True)
    unit=models.CharField(max_length=50,null=True,blank=True)
    rate=models.DecimalField(max_digits=12,decimal_places=2,null=True,default=None)
    quantity=models.DecimalField(max_digits=15,decimal_places=2,null=True,default=None)
    amount=models.DecimalField(max_digits=20,decimal_places=2,null=True,blank=True)
    heading=models.BooleanField(null=True,default=True) 
    subheading=models.CharField(max_length=10,null=True,blank=True) # serialno+'&&&'+subheading if subheading found above a row
    work_order_date=models.DateField()
    extra_item=models.BooleanField(default=False)#if item is added later as extra
    other_details=models.CharField(max_length=500,null=True,blank=True)
    def __str__(self):
        return "{},project={} ,{},{},{},{},{},{},{}".format(self.pk,self.project.project_name,self.serial_no,self.description,self.rate,self.unit,self.quantity,self.amount,self.subheading)
    
    class Meta:
        db_table = 'WOBOQItem'
        
class Measurement(models.Model):
    woboqitem=models.ForeignKey(WOBOQItem,on_delete=models.CASCADE)
    bill=models.ForeignKey(Bill,on_delete=models.CASCADE)
    m_description=models.CharField(max_length=500,null=True,blank=True)
    count=models.IntegerField(default=1,help_text="the number of items with this measurement")
    number=models.DecimalField(max_digits=10,decimal_places=3,null=True,default=1.000)
    length=models.DecimalField(max_digits=16,decimal_places=3,null=True,default=1.000)
    breadth=models.DecimalField(max_digits=16,decimal_places=3,default=1.000,null=True)
    height=models.DecimalField(max_digits=16,decimal_places=3,default=1.000,null=True)
    quantity=models.DecimalField(max_digits=16,decimal_places=3,default=0.000,null=True)
    entry_date=models.DateField() 
    consultant_approved=models.DateTimeField(null=True,blank=True,default=None)
    owner_approved=models.DateTimeField(null=True,blank=True,default=None)     
    other_details=models.CharField(max_length=500,null=True,blank=True)
    def __str__(self):
        return "{} : {}".format(self.woboqitem.description,self.quantity)
    
    class Meta:
        db_table = 'Measurement'

class Consultant_Comments(models.Model):
    measurement=models.ForeignKey(Measurement,on_delete=models.CASCADE)
    commented_on=models.DateTimeField(default=now) 
    comment=models.CharField(max_length=1000,null=True,blank=True)
    measurement_backup=models.CharField(max_length=500,null=True,blank=True)
    status=models.CharField(max_length=10,null=True,default='open') #open,closed
    read_by_project=models.BooleanField(null=True,default=False) 
    def __str__(self):
        return "{},{}".format(self.comment,self.measurement_backup)
    
    class Meta:
        db_table = 'Consultant_Comments'


class Owner_Comments(models.Model):
    measurement=models.ForeignKey(Measurement,on_delete=models.CASCADE)
    commented_on=models.DateTimeField(default=now)    
    comment=models.CharField(max_length=1000,null=True,blank=True)
    measurement_backup=models.CharField(max_length=500,null=True,blank=True)
    status=models.CharField(max_length=10,null=True,default='open') #open or closed, status by owner
    read_by_project=models.BooleanField(null=True,default=False) 
    read_by_consultant=models.BooleanField(null=True,default=False)
    consultant_status=models.CharField(max_length=10,null=True,default='open') #staus by consultant
    def __str__(self):
        return "{}".format(self.measurement_backup)
     
    class Meta:
        db_table = 'Owner_Comments' 

class COPMaster(models.Model):
    project=models.ForeignKey(Project,on_delete=models.CASCADE)     
    company_logo=models.CharField(max_length=500,null=True,blank=True)
    gst_no=models.CharField(max_length=50,null=True,blank=True)

    state=models.CharField(max_length=100,null=True,blank=True)
    bank=models.CharField(max_length=200,null=True,blank=True)
    branch=models.CharField(max_length=200,null=True,blank=True)

accounts/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth import login,authenticate,logout
from .models import User
from django.http import JsonResponse
def LoginView(request):
    if request.method == 'POST':
        user_name=request.POST.get('username')
        pw=request.POST.get('password')
        user=authenticate(request,username=user_name,password=pw)
        if user is not None:
            currentuser=User.objects.get(username=user_name)
            login(request,user)            
            if currentuser.user_type == 'project':
                return redirect('project:Dashboard')
            if currentuser.user_type == 'company':
                return redirect('company:Dashboard')
            if currentuser.user_type == 'consultant':
                return redirect('consultant:Dashboard')
            if currentuser.user_type == 'owner':
                return redirect('owner:Dashboard')
            return render(request,'accounts/loginpage.html',{'msg':'Unknown user type, Please login using valid credentials'})
        else:
            return render(request,'accounts/loginpage.html',{'msg':'Unknown user, Please login using valid credentials'})

    return render(request,'accounts/loginpage.html')

def ajax_email_exists(request):
    try:
        emailids=User.objects.values_list('email', flat=True)
        emailid =request.GET.get('email')
        if emailid in emailids:
            return JsonResponse({'result':'reject'})
    except:
        pass
    return JsonResponse({'result':'accept'})
def ajax_email_exists_edit(request):
    try:
        emailids=User.objects.values_list('email', flat=True)
        emailid =request.GET.get('email')
        print(emailid)

        existingemail=request.GET.get('existingemail')
        print(existingemail)
        if emailid in emailids :
            if emailid == existingemail:
                return JsonResponse({'result':'accept'})
            else:
                return JsonResponse({'result':'reject'})
    except:
        pass
    return JsonResponse({'result':'accept'})


from django.contrib.auth.decorators import login_required
@login_required
def userlogout(request):   
    logout(request)
    return redirect('accounts:UserLogin')

accounts/templates/accounts/loginpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">
    
</head>
<body>
    {% if messages %}
    <div class="mt-3">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="login-box">
        <center>
            <div class="logo">
                <img src="{% static 'accounts/images/logo.png' %}" alt="Logo" class="login-logo p-3">
            </div>       

        </center>       
        
        <form action="{% url 'accounts:UserLogin' %}" method="post">
            {% csrf_token %}
            <div class="my-3">
                <input type="text" class="form-control" name="username" id="username" placeholder="Username" autocomplete="off">
            </div>
            <div class="mb-4">
                <input type="password" name="password" class="form-control" id="password" placeholder="Password" autocomplete="off">
            </div>
            <button type="submit" class="btn btn-custom btn-block w-100 mb-3">Log In Now</button>
            <a href="{% url 'accounts:PasswordReset' %}" class="fw-bolder">Forgot password ?</a>
        </form>
        {% if msg %}
        <h6 class="text-danger fw-bolder m-3">{{msg}}</h6>
        {% endif %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

accounts/templates/accounts/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ForgotPassword</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">
    
</head>
<body>
    <div class="login-box">
    
        <h4 class="text-center">Forgot Password</h2>
        <hr class="mb-5">
        <form method="post" action="{% url 'accounts:PasswordReset' %}" class="d-flex align-items-center">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-custom py-1 ms-4">Submit</button>
            
        </form>
        <p class="text-danger fw-bolder" style="font-size: smaller;">CAUTION: Enter your registered email id only.</p>
        
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

accounts/templates/accounts/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ForgotPassword</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">
    
</head>
<body>
    <div class="login-box">
        <h3>Password reset complete</h3>
        <hr>

        <a href="{% url 'accounts:UserLogin' %}" class="btn btn-custom">Click here to Login</a>
    </div>
    
</body>
</html>

accounts/templates/accounts/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ForgotPassword</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">
    
</head>
<body>
    <div class="login-box text-secondary">
    {% if validlink %} 
        
        <h4 class="text-center">Change Password</h2>
        <hr class="mb-5">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-custom py-1 ms-4">Change Password</button>            
        </form>        
    
    {% else %}
    <h4 class="text-center">Link Expired</h2>
    <hr class="mb-5">
    <p>Password reset link was invalid, possibly because it has already been used.Please use a new password reset link.</p>
    {% endif %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

accounts/templates/accounts/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ForgotPassword</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">
    
</head>
<body>
    <div class="bg-light p-3">
        <h3>Password reset sent</h3>

        <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
        </p>
        <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
        </p>
    </div>
    
</body>
</html>

accounts/templates/accounts/password_reset_email.html
{% load i18n %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at Arghya Solutions.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{{ protocol }}://{{ domain }}{% url 'accounts:PasswordResetConfirm' uidb64=uid token=token %}

{% translate "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% blocktranslate %}Thanks for using our site!{% endblocktranslate %}