CONSTRUCTION_BILLING_PRJ/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include("accounts.urls")),
    path('companies/',include("company.urls")),
    path('projects/',include("project.urls")),
    path('consultants/',include("consultant.urls")),
    path('clients/',include("owner.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path,include
from . views import *
app_name='project'
urlpatterns = [
    path('',dashboard,name='Dashboard'),
    path('manage',manage_project,name='ManageProject'),    
    path('edit',edit_project,name='EditProject'),   
    path('change_password',change_password,name='ChangePassword'),
    path('ajax_get_headings',ajax_get_headings,name='AjaxGetHeadings'),
    path('upload-status',get_upload_status, name='GetUploadStatus'),
    path('get_billupload_status',get_billupload_status, name='GetBillUploadStatus'),

    path('search_BoQ/<int:page>',search_boq_item,name='SearchItem'), 
    path('bill_of_quantities/<int:page>',manage_bill_of_quantities,name='ManageBOQ'),
    path('confirm_delete/<int:id>',confirm_delete_boq,name='ConfirmRemoveBOQ'),
    path('bill_of_quantities/delete',delete_bill_of_quantities,name='RemoveBOQ'),
    path('manage_item/<int:itemid>',manage_boq_item,name='ManageItem'), 
    path('remove_item/<int:itemid>',remove_boq_item,name='DeleteItem'), 

    path('boq_approvals',view_boq_approvals,name='ViewBoqApprovals'),
    path('remove_boq_update/<int:id>',remove_boq_update,name='RemoveBoqItemUpdate'),

    path('get_owners',ajax_get_owners,name='AjaxGetOwners'),
    path('get_companies',ajax_get_companies,name='AjaxGetCompanies'),
    path('get_consultants',ajax_get_consultants,name='AjaxGetConsultants'),

    path('add_consultant',add_consultant,name='AddConsultant'), 
    path('add_company',add_company,name='AddCompany'), 
    path('add_owner',add_owner,name='AddOwner'), 
    
    path('owner_comments/<int:measureid>',view_owner_comments,name='ViewOwnerComments'), 
    path('measurements/<int:itemid>/<int:page>',manage_measurements,name='Measurements'),
    path('edit_measurement/<int:measurementid>',edit_measurement,name='EditMeasurement'),
    path('remove_measurement/<int:measurementid>',remove_measurement,name='DeleteMeasurement'),
    path('workorder_boq/',upload_workorder_boq,name='UpLoadWOBOQ'),     
    path('bills/',create_bill,name='CreateBill'),
    path('create_new_bill/',create_new_bill,name='CreateNewBill'), 
    path('current_bill/<int:page>',current_bill,name='CurrentBill'), 
    path('save_current_bill',save_current_bill,name='SaveCurrentBill'),

    path('previous_bills',previous_bills,name='PreviousBills'), 
    path('previous_bills/<int:billid>/<int:page>',previous_bill,name='PreviousBill'), 
    path('previous_bills/measurements/<int:billid>/<int:itemid>/<int:page>',previous_bill_measurements,name='PreviousMeasurements'),
    path('edit_measurement/<int:measurementid>',edit_measurement,name='EditMeasurement'),
    path('remove_previous_measurement/<int:billid>/<int:measurementid>',remove_prev_measurement,name='DeletePreviousMeasurement'),
    path('search_item/<int:billid>/<int:page>',search_bill_item,name='SearchBillItem'), 
    path('share_to_consultant/<int:billid>',share_to_consultant,name='ShareToConsultant'),

    

    path('view_abstract/<int:billid>/<int:page>',viewAbstract,name='ViewAbstract'),
    path('generate_documents',generate_documents,name='Documents'),
    path('measurement_book/<int:billid>',downloadMBook,name='DownloadMBook'),
    
    path('logout_project/',userlogout,name='LogOutUser'),  
]

project/models.py
from django.db import models

# Create your models here.

project/views.py
from django.shortcuts import render,redirect
from .decorators import project_required
from accounts.models import *
from django.contrib.auth import authenticate,logout
from django.http import HttpResponseBadRequest,JsonResponse,HttpResponse
import pandas as pd
import openpyxl
from . utilities import *
from decimal import Decimal
from django.core.paginator import Paginator
from django.db.models import Sum
from openpyxl.styles import Font,PatternFill,Alignment,colors,Border,Side,NamedStyle
from openpyxl.drawing.image import Image
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.utils.timezone import now
from django.contrib import messages



@project_required
def dashboard(request):
    try:
        # companies=''
        # consultants=''
        # owners=''
        currentuser=request.user
        projectobjs=Project.objects.values_list('user', flat=True)
        print(projectobjs)        
        if currentuser.id in projectobjs:
            projectobj=Project.objects.get(user=currentuser)
            bills=Bill.objects.filter(project=projectobj)
            activebill=Bill.objects.filter(project=projectobj,submitted=False).count()
            wo_boq_uploaded=WOBOQItem.objects.filter(project=projectobj).exists()
            if wo_boq_uploaded:
                boq_approve_count=Pending_Item.objects.filter(project=projectobj).count()
            else:
                boq_approve_count=0
            context={
                'registered' :True,
                'workorder_uploaded':wo_boq_uploaded,
                'projectobj' : projectobj, 
                'bills':bills,
                'billcount':bills.count(),
                'activebill':activebill,
                'boq_approve_count':boq_approve_count           
            }            
        else:            
            context={
                'registered' :False,                
            }
        return render(request,'project/dashboard.html',context)
    except Exception as e:
        context={
                'registered' :'Error',            
            }
        messages.error(request, "Something went wrong : "+str(e))
        return render(request,'project/dashboard.html',context) 
    
@project_required
def ajax_get_owners(request):
    query = request.GET.get('q', '')
    if query and len(query) >= 4:
        # Case-insensitive search for matching usernames
        owners = Owner.objects.filter(owner_name__icontains=query).values('id', 'owner_name')#[:10]  # Limit results
        return JsonResponse(list(owners), safe=False)
    return JsonResponse([], safe=False) 

from django.shortcuts import get_object_or_404
@project_required
def ajax_get_consultants(request):
    owner_id = request.GET.get('owner_id')  # Retrieve the owner_id from the GET request
    if owner_id:
        # Query consultants associated with the owner (adjust according to your model)
        owner=Owner.objects.get(id=owner_id)
        consultants=[]
        if owner:
            consultants = Consultant.objects.filter(owner=owner)
        # Prepare data to send back as JSON
        data = [{'id': consultant.id, 'consultant_name': consultant.consultant_name} for consultant in consultants]
        print('consultants found>>>>>>>')
        print(data)
        return JsonResponse(data, safe=False)
    return JsonResponse({'error': 'No owner_id provided'}, status=400)

@project_required
def ajax_get_companies(request):
    query = request.GET.get('q', '')
    if query and len(query) >= 4:
        # Case-insensitive search for matching usernames
        companies = Company.objects.filter(company_name__icontains=query).values('id', 'company_name')#[:10]  # Limit results
        print('companies found>>>>>>>')
        print(companies)
        return JsonResponse(list(companies), safe=False)
    return JsonResponse([], safe=False)


@project_required
def add_consultant(request):
    current_user=request.user    
    msg=''
    try:
        if request.method == 'POST':            
            name=request.POST.get('consultantcompanyname')
            emailid=request.POST.get('consultantemailid')
            username,password=get_username_password(name)
            print('username =',username)
            print('password =',password)
            address=request.POST.get('consultantaddress')
            country_code=request.POST.get('consultantcountrycode')
            phone=request.POST.get('consultantphone')
            owner_id=request.POST.get('ownerid')
            print('OWNER ID=',owner_id)
            owner=Owner.objects.get(id=owner_id)
            
            if User.objects.filter(username=username).exists():
                return JsonResponse({'error': 'Already exists.'}, status=400)               
            else:
                with transaction.atomic():
                    epassword=make_password(password)
                    user=User.objects.create(first_name=name,username=username,password=epassword,is_staff=False,email=emailid,user_type='consultant',added_by=current_user.username,is_active=False)
                    print('new user=',user)
                    newconsultant=Consultant.objects.create(
                    user=user,
                    consultant_name=name,
                    consultant_address=address,
                    consultant_email=emailid,
                    country_code=country_code,
                    consultant_phone=phone,
                    owner=owner
                                    
                    )  
                    
                    recipient_list = [emailid] 
                    context = {
                        'consultantusername': username,
                        'consultantname': name,
                        'password': password,
                        'contractor': current_user.first_name,
                    }
                    transaction.on_commit(lambda: send_user_email.delay(context,'consultant',recipient_list))

                        
                    return JsonResponse({'message': 'Consultant added successfully!','id':newconsultant.id,'name':newconsultant.consultant_name})
        return JsonResponse({'error': 'Invalid request method.'}, status=400) 
    except Exception as e:
        messages.error(request, "Error : "+str(e))
        print(e)                
    return JsonResponse({'error': 'Invalid request method.'}, status=400)    

@project_required
def add_company(request):
    current_user=request.user    
    msg=''
    try:
        if request.method == 'POST':            
            name=request.POST.get('contractorcompanyname')
            emailid=request.POST.get('companyemailid')
            username,password=get_username_password(name)
            print('username =',username)
            print('password =',password)
            address=request.POST.get('companyaddress')
            country_code=request.POST.get('companycountrycode')
            phone=request.POST.get('companyphone')
            
            if User.objects.filter(username=username).exists():
                return JsonResponse({'error': 'Already exists.'}, status=400)               
            else:
                with transaction.atomic():
                    epassword=make_password(password)
                    user=User.objects.create(first_name=name,username=username,password=epassword,is_staff=False,email=emailid,user_type='company',added_by=current_user.username,is_active=False)
                    print('new user=',user)
                    newcompany=Company.objects.create(
                    user=user,
                    company_name=name,
                    company_address=address,
                    company_email=emailid,
                    country_code=country_code,
                    company_phone=phone,                                    
                    )  
                    
                    recipient_list = [emailid] 
                    context = {
                        'companyusername': username,
                        'companyname': name,
                        'password': password,
                        'projectname': current_user.first_name,
                    }
                    transaction.on_commit(lambda: send_user_email.delay(context,'company',recipient_list))

                        
                    return JsonResponse({'message': 'Company added successfully!','id':newcompany.id,'name':newcompany.company_name})
        return JsonResponse({'error': 'Invalid request method.'}, status=400) 
    except Exception as e:
        messages.error(request, "Error : "+str(e))
        print(e)                
    return JsonResponse({'error': 'Invalid request method.'}, status=400)        


@project_required
def add_owner(request):
    current_user=request.user    
    msg=''
    try:
        if request.method == 'POST':            
            name=request.POST.get('ownercompanyname')
            emailid=request.POST.get('owneremailid')
            username,password=get_username_password(name)
            print('username =',username)
            print('password =',password)
            address=request.POST.get('owneraddress')
            country_code=request.POST.get('ownercountrycode')
            phone=request.POST.get('ownerphone')
            
            if User.objects.filter(username=username).exists():
                return JsonResponse({'error': 'Already exists.'}, status=400)               
            else:
                with transaction.atomic():
                    epassword=make_password(password)
                    user=User.objects.create(first_name=name,username=username,password=epassword,is_staff=False,email=emailid,user_type='owner',added_by=current_user.username,is_active=False)
                    print('new user=',user)
                    newowner=Owner.objects.create(
                    user=user,
                    owner_name=name,

project/templates/project/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ArghyaBilling-Project</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'project/css/style.css' %}">
    
 </head>
 <body >    
    <nav class="navbar navbar-expand-lg  mt-5 shadow-lg p-3">
        <div class="row w-100">
            <div class="col">                  
                <img src="{% static 'project/images/roundlogo.png'%}"  style="height: 70px;width: auto;border: 0px;border-radius: 50px;">                    
                    
            </div>
            <div class="col">
                <a class="navbar-brand btn btn-custom " href="{% url 'project:Dashboard' %}">Dashboard</a>
            </div>  
            <div class="col">
                <a class="navbar-brand btn btn-custom " href="{% url 'project:ManageBOQ' 1 %}">Manage BoQ</a>
            </div>          
            <div class="col">
                <a class="navbar-brand btn btn-custom " href="{% url 'project:CurrentBill' 1 %}">Manage Current Bill</a>
            </div>
            <div class="col">
                <a class="navbar-brand btn btn-custom " href="{% url 'project:PreviousBills' %}">Manage Previous Bill</a>
            </div>
            
           <div class="col">
                <a class="navbar-brand btn btn-custom " href="{% url 'project:Documents' %}">Downloads</a>
            </div>
            {% block navcontent %}
      
            {% endblock %}
            <div class="col" style="text-align: right;">
                <div class="badge bg-primary text-light p-2 shadow-lg"> Welcome {{user.username}} ! </div>
             </div>
            <div class="col-md-2 text-center">
                <!-- Inline buttons and text -->
                <div class="inline-items">
                    
                    <a href="{% url 'project:ChangePassword' %}" class="btn  btn-custom" >Manage Account</a> 
                    <a href="{% url 'project:LogOutUser' %}" class="btn  btn-custom" >Logout</a>
                </div>
            </div>            
        </div>
    </nav>
    {% if messages %}
    <div class="mt-3">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible show fw-bolder h3" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}
    {% block maincontent %}
      
    {% endblock %}
   
  
<script> 
    const images = [
        "url('{% static 'project/images/bg1.jpg' %}')",
        "url('{% static 'project/images/bg2.jpg' %}')",
        "url('{% static 'project/images/bg3.jpg' %}')"
    ];
    let currentIndex = 0;

    function changeBackground() {
        document.body.style.backgroundImage = images[currentIndex];    
        document.body.style.backgroundSize = 'cover';  // Ensures the image covers the entire screen
        document.body.style.backgroundPosition = 'center';  // Centers the image
        document.body.style.backgroundRepeat = 'no-repeat';  // Prevents image repetition
        currentIndex = (currentIndex + 1) % images.length;
    }


    document.addEventListener('DOMContentLoaded', () => {    
        changeBackground();
        setInterval(changeBackground, 3600000);
    });
    

    
</script>
 
 <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
 <script src="{% static 'project/js/script.js' %}"></script>
 {% block scripts %}
 <!-- Block for additional scripts in child templates -->
 {% endblock %}
</body>
 </html>

project/templates/project/current_bill.html
{% extends 'project/base.html' %}
{% load static %}
{% load custom_filters %}

{% block navcontent %}
{% endblock %}
{% block maincontent %}

<h3 class="text-light fw-bolder" style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.9);">PROJECT : CURRENT BILL</h3>
{% if msg %}
<div class="card mt-3" >
    <h2 class="form-heading bg-light text-danger fw-bolder m-3" style="width: fit-content;">{{msg}}</h2>
</div>

{% endif %}   
{% if not page_object %} 
<div class="card " >
    <h2 class="form-heading bg-light text-danger fw-bolder m-3">No data found...</h2>
</div>

{% endif %} 
    
         
        
{% if current_bill %} 
    <div class="card border-primary m-2 p-2" style="background-color: rgba(255, 255, 255, 0.253)"> 
        <a href="{% url 'project:CurrentBill' 1  %}" class="text-light" style='font-size:25px' >
            <i class='fas fa-redo text-light' style='font-size:25px'></i>
            Refresh {{current_bill.bill_name}}
        </a>     
        {% if page_object %}    
        
        <div class="row bg-light p-3 m-3"> 
            <h4 class="m-3 fw-bold">Bill Details </h4>  
            <hr>     
            <div class="col">            
                <h6 class="fw-bold ms-3">Bill Count :{{ current_bill.bill_number }} </h6>          
            </div>
            <div class="col">
                <h6 class="fw-bold">Bill Name :{{ current_bill.bill_name }} </h6>                    
            </div>
            <div class="col">
                <h6 class="fw-bold">Bill Date :{{ current_bill.bill_date }} </h6>              
            </div>
            <div class="col">
                {% if not current_bill.submitted %} 
                <span>
                    <a href="{% url 'project:SaveCurrentBill' %}" class="btn btn-custom">Finish {{ current_bill.bill_name }}</a>
                    <small style="font-size: 15px;font-weight: bold;color: orangered;">Finish this bill to create next bill</small>
                </span>
                {% endif %}                         

                            
            </div>
        </div>
        <div class="row m-3">{{current_bill.other_details}}</div>
        <div class="row bg-light p-3 m-3">
            <h4 class="m-3 text-primary fw-bold">Approvals</h4>             
            <div class="col">
                {% if current_bill.consultant_approved %} 
                    <p><i class="fas fa-user-check py-2 text-success"></i>Approved by Consultant on {{current_bill.consultant_approved|to_ist}}.</p>
                {% elif current_bill.shared_to_consultant %} 
                    <p>{{current_bill.bill_name}} Shared with Consultant for approval on {{ current_bill.shared_to_consultant|to_ist}}.</p>
                {% else %} 
                    <a href="{% url 'project:ShareToConsultant' current_bill.id %}" class="btn btn-custom"><i class="fas fa-share py-2"></i> Share {{ current_bill.bill_name }} to Consultant</a>
                {% endif %}  
            </div>
            <div class="col">
                {% if current_bill.owner_approved %} 
                    <p><i class="fas fa-user-check py-2 text-success"></i>Approved by Owner/client on {{current_bill.owner_approved|to_ist }}.</p>
                {% elif current_bill.shared_to_owner %} 
                    <p>{{current_bill.bill_name}} Shared with Owner for approval on {{ current_bill.shared_to_owner|to_ist}}</p>
                {% endif %}   
            </div>

        </div>
    </div>

    <div class="card border border-primary p-2 mx-1" style="background-color: rgba(255, 255, 255, 0.253)">
        <div class="inline-items">
            <span class=" bg-secondary border border-primary  text-light p-3 fw-bold">Total Pages : {{page_object.paginator.num_pages}} </span>
            {% if page_object.has_previous %}
                <a href="{% url 'project:CurrentBill' page_object.number|add:'-1' %}" class="btn btn-custom m-1 rounded-circle"><i class="fas fa-reply text-primary py-2"></i></a> 
            {% endif %}
            <span class="mx-2 bg-secondary border border-primary  text-light p-3"><b>Current Page : {{page_object.number}}</b></span>
            {% if page_object.has_next %}
                <a href="{% url 'project:CurrentBill' page_object.number|add:'1' %}" class="btn btn-custom m-1 rounded-circle"><i class="fas fa-share text-primary py-2"></i></a> 
            {% endif %}
            <span class="ms-5 mx-2 p-3 text-light">  
                <form id="phonesearchfrm" action="{% url 'project:SearchItem' 1 %}" class="bg-secondary border border-primary " method="post">
                {% csrf_token %}
                    <div class="input-group inline text-light border-2 border-dark" >                    
                        <input type="search" id="searchitem"  name="searchitem" class="inline fw-bold w-auto bg-secondary text-light border border-0 px-5" placeholder="Enter item to search....">
                        <button type="submit" class="btn bg-light text-primary rounded-circle ms-1 my-2"><i class="fa fa-search" aria-hidden="true"></i></button>
                    </div>
                </form>
                <small style="font-size: 15px;font-weight: bold;color: orangered;">*Search item by description</small>
                
            </span>  
        </div>
        
        <table class="table bg-light border border-primary p-3 shadow-lg" name="billtable" id="billtable" >
            <thead class="bg-secondary text-light">
                <tr>
                    <th scope="col" style="width: 150px;">DATE</th> 
                    <th scope="col">SL NO</th>
                    <th scope="col">ITEM DESCRIPTION</th>                                         
                    <th scope="col">MBOOK</th>
                    {% if current_bill.shared_to_consultant %}
                    <th scope="col">CONSULTANT</th>
                    {% endif %}
                    {% if current_bill.shared_to_owner %}
                    <th scope="col">OWNER</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody >
                {% for object in page_object %}
                    {% if not object.extra_item %}
                        {% if object.heading %}
                            <tr> 
                                <td></td>                                
                                {% if object.serial_no == 'nan' %}  
                                    <td></td>  
                                {% else %}                            
                                    <td class="fw-bolder">{{object.serial_no}}</td>
                                {% endif %}
                                <td class="fw-bolder">{{object.description}}</td>   
                                <td class="fw-bolder"></td>  
                                {% if current_bill.shared_to_consultant %}
                                <td ></td>
                                {% endif %}
                                                                                      
                            </tr>
                        {% else %}                        
                            <tr >
                                <th scope="row">{{object.work_order_date}}</th>
                                {% if object.serial_no == 'nan' %}  
                                    <td></td>  
                                {% else %}                            
                                    <td>{{object.serial_no}}</td>
                                {% endif %}
                                
                                <td >{{object.description}}</td>                
                                
                                <td>
                                    <a href="{% url 'project:Measurements' object.id 1 %}">+Measurements</a>
                                </td> 
                                {% if current_bill.shared_to_consultant %}
                                <td ><a href="{% url 'project:ConsultantApprovals' current_bill.id object.id 1 %}">Approvals</a></td>
                                {% endif %}
                                            
                                
                            </tr>
                        {% endif %}
                    {% else %}
                        <!-- {% if object.subheading %} 
                            <tr >
                                <td></td>
                                {% with object.subheading|split:"&&&" as parts %}
                                <td class="text-primary fw-bolder">{{ parts.0 }}</td>
                                <td class="text-primary fw-bolder">{{ parts.1 }}</td>
                                {% endwith %}
                            </tr>        
                        {% endif %} -->
                        <tr >
                            <th scope="row">{{object.work_order_date}}</th>
                            {% if object.serial_no == 'nan' %}  
                                <td></td>  
                            {% else %}                            
                                <td>{{object.serial_no}}</td>
                            {% endif %}
                            
                            <td ><p style="color: rgb(255, 0, 55);font-size:20px;">Extra Item : </p>{{object.description}}</td>                
                            
                            <td>
                                <a href="{% url 'project:Measurements' object.id 1 %}">+Measurements</a>
                            </td>
                            {% if current_bill.shared_to_consultant %}
                                <td ><a href="{% url 'project:ConsultantApprovals' current_bill.id object.id 1 %}">Approvals</a></td>
                            {% endif %}
                            <!-- {% if current_bill.shared_to_owner %}
                            <td >Approvals</td>
                            {% endif %}  -->
                            <!-- <td>
                                <a href="" class="btn btn-custom m-1 rounded-circle">
                                <i class='fas fa-trash py-2' style='color:red;font-size:20px;'></i></a>
                            </td> -->
                        </tr>                    
                    {% endif %}
                {% endfor %}
                
            </tbody>
        </table>
        
        <div class="inline-items">
            <span class="mx-2 bg-secondary border border-primary  text-light p-3 fw-bold">Total Pages : {{page_object.paginator.num_pages}} </span>
            {% if page_object.has_previous %}
                <a href="{% url 'project:CurrentBill' page_object.number|add:'-1' %}" class="btn btn-custom m-1 rounded-circle"><i class="fas fa-reply text-primary py-2"></i></a> 
            {% endif %}
            <span class="mx-2 bg-secondary border border-primary  text-light p-3"><b>Current Page : {{page_object.number}}</b></span>
            {% if page_object.has_next %}
                <a href="{% url 'project:CurrentBill' page_object.number|add:'1' %}" class="btn btn-custom m-1 rounded-circle"><i class="fas fa-share text-primary py-2"></i></a> 
            {% endif %}
            <span class="ms-5 mx-2 p-3 text-light">  
                <form id="phonesearchfrm" action="{% url 'project:SearchItem' 1 %}" class="bg-secondary border border-primary " method="post">
                {% csrf_token %}
                    <div class="input-group inline text-light border-2 border-dark" >                    
                        <input type="search" id="searchitem"  name="searchitem" class="inline fw-bold w-auto bg-secondary text-light border border-0 px-5" placeholder="Enter item to search....">
                        <button type="submit" class="btn bg-light text-primary rounded-circle ms-1 my-2"><i class="fa fa-search" aria-hidden="true"></i></button>
                    </div>
                </form>
                <small style="font-size: 15px;font-weight: bold;color: orangered;">*Search item by description</small>
                
            </span> 
            
        </div>

        
    {% endif %}
    </div>
{% elif page_object.paginator %}
  <center>
    <a href="{% url 'project:CreateBill' %}" class="btn btn-custom p-3 fs-3 text m-4">Create New Bill</a>
  </center>  
   
{% endif %}     
{% endblock %}

{% block scripts %}
    {{ block.super }} 

    <script src="{% static 'project/js/current_bill.js' %}"></script> 
{% endblock %}